from .nodes.boolean_list import (
    NODE_CLASS_MAPPINGS as BOOLEAN_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_DISPLAY_NAME_MAPPINGS,
)
from .nodes.boolean_list_hierarchy import (
    NODE_CLASS_MAPPINGS as BOOLEAN_HIERARCHY_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_HIERARCHY_DISPLAY_NAME_MAPPINGS,
)
from .nodes.boolean_list_hierarchy_get import (
    NODE_CLASS_MAPPINGS as BOOLEAN_HIERARCHY_GET_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_HIERARCHY_GET_DISPLAY_NAME_MAPPINGS,
)
from .nodes.boolean_group_bypass_controller import (
    NODE_CLASS_MAPPINGS as BOOLEAN_GROUP_CONTROLLER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_GROUP_CONTROLLER_DISPLAY_NAME_MAPPINGS,
)
from .nodes.seedream_exhibition_prompt_builder import (
    NODE_CLASS_MAPPINGS as SEEDREAM_EXHIBITION_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEEDREAM_EXHIBITION_DISPLAY_NAME_MAPPINGS,
)
from .nodes.gpt_image2_config import (
    NODE_CLASS_MAPPINGS as GPT_IMAGE2_CONFIG_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE2_CONFIG_DISPLAY_NAME_MAPPINGS,
)
from .nodes.gpt_image2_material_prompt import (
    NODE_CLASS_MAPPINGS as GPT_IMAGE2_MATERIAL_PROMPT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE2_MATERIAL_PROMPT_DISPLAY_NAME_MAPPINGS,
)
from .nodes.badge_relief_prompt import (
    NODE_CLASS_MAPPINGS as BADGE_RELIEF_PROMPT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BADGE_RELIEF_PROMPT_DISPLAY_NAME_MAPPINGS,
)
from .nodes.multi_color_mask import (
    NODE_CLASS_MAPPINGS as MULTI_COLOR_MASK_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MULTI_COLOR_MASK_DISPLAY_NAME_MAPPINGS,
)
from .nodes.badge_height_layer import (
    NODE_CLASS_MAPPINGS as BADGE_HEIGHT_LAYER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BADGE_HEIGHT_LAYER_DISPLAY_NAME_MAPPINGS,
)
from .nodes.badge_workflow import (
    NODE_CLASS_MAPPINGS as BADGE_WORKFLOW_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BADGE_WORKFLOW_DISPLAY_NAME_MAPPINGS,
)
from .nodes.rmbg_config import (
    NODE_CLASS_MAPPINGS as RMBG_CONFIG_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RMBG_CONFIG_DISPLAY_NAME_MAPPINGS,
)
from .nodes.app_mode_load_image import (
    NODE_CLASS_MAPPINGS as APP_MODE_LOAD_IMAGE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as APP_MODE_LOAD_IMAGE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.bbox_prompt_reroute import (
    NODE_CLASS_MAPPINGS as BBOX_REROUTE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BBOX_REROUTE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.sam3_complex_collector import (
    NODE_CLASS_MAPPINGS as SAM3_COMPLEX_COLLECTOR_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAM3_COMPLEX_COLLECTOR_DISPLAY_NAME_MAPPINGS,
)
from .nodes.polygon_mask import (
    NODE_CLASS_MAPPINGS as SIMPLE_POLYGON_MASK_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_POLYGON_MASK_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(BOOLEAN_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BOOLEAN_HIERARCHY_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BOOLEAN_HIERARCHY_GET_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BOOLEAN_GROUP_CONTROLLER_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SEEDREAM_EXHIBITION_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GPT_IMAGE2_CONFIG_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GPT_IMAGE2_MATERIAL_PROMPT_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BADGE_RELIEF_PROMPT_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MULTI_COLOR_MASK_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BADGE_HEIGHT_LAYER_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BADGE_WORKFLOW_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(RMBG_CONFIG_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(APP_MODE_LOAD_IMAGE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BBOX_REROUTE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SAM3_COMPLEX_COLLECTOR_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SIMPLE_POLYGON_MASK_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_HIERARCHY_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_HIERARCHY_GET_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_GROUP_CONTROLLER_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SEEDREAM_EXHIBITION_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GPT_IMAGE2_CONFIG_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GPT_IMAGE2_MATERIAL_PROMPT_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BADGE_RELIEF_PROMPT_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MULTI_COLOR_MASK_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BADGE_HEIGHT_LAYER_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BADGE_WORKFLOW_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RMBG_CONFIG_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(APP_MODE_LOAD_IMAGE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BBOX_REROUTE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SAM3_COMPLEX_COLLECTOR_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SIMPLE_POLYGON_MASK_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
from .nodes.badge_strict_material import (
    NODE_CLASS_MAPPINGS as BADGE_STRICT_MATERIAL_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BADGE_STRICT_MATERIAL_DISPLAY_NAME_MAPPINGS,
)
NODE_CLASS_MAPPINGS.update(BADGE_STRICT_MATERIAL_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BADGE_STRICT_MATERIAL_DISPLAY_NAME_MAPPINGS)
