from .nodes.boolean_list import (
    NODE_CLASS_MAPPINGS as BOOLEAN_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_DISPLAY_NAME_MAPPINGS,
)
from .nodes.gpt_image_prompt_preset import (
    NODE_CLASS_MAPPINGS as GPT_IMAGE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.load_image_boolean_bbox import (
    NODE_CLASS_MAPPINGS as BBOX_LOADER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BBOX_LOADER_DISPLAY_NAME_MAPPINGS,
)
from .nodes.bbox_prompt_reroute import (
    NODE_CLASS_MAPPINGS as BBOX_REROUTE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BBOX_REROUTE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.load_image_polygon_mask import (
    NODE_CLASS_MAPPINGS as POLYGON_MASK_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as POLYGON_MASK_DISPLAY_NAME_MAPPINGS,
)
from .nodes.sam3_complex_collector import (
    NODE_CLASS_MAPPINGS as SAM3_COMPLEX_COLLECTOR_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAM3_COMPLEX_COLLECTOR_DISPLAY_NAME_MAPPINGS,
)
from .nodes.polygon_mask import (
    NODE_CLASS_MAPPINGS as SIMPLE_POLYGON_MASK_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_POLYGON_MASK_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(BOOLEAN_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GPT_IMAGE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BBOX_LOADER_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BBOX_REROUTE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(POLYGON_MASK_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SAM3_COMPLEX_COLLECTOR_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SIMPLE_POLYGON_MASK_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GPT_IMAGE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BBOX_LOADER_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BBOX_REROUTE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(POLYGON_MASK_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SAM3_COMPLEX_COLLECTOR_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SIMPLE_POLYGON_MASK_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]