from .nodes.boolean_list import (
    NODE_CLASS_MAPPINGS as BOOLEAN_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_DISPLAY_NAME_MAPPINGS,
)
from .nodes.boolean_list_hierarchy import (
    NODE_CLASS_MAPPINGS as BOOLEAN_HIERARCHY_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_HIERARCHY_DISPLAY_NAME_MAPPINGS,
)
from .nodes.boolean_group_bypass_controller import (
    NODE_CLASS_MAPPINGS as BOOLEAN_GROUP_CONTROLLER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_GROUP_CONTROLLER_DISPLAY_NAME_MAPPINGS,
)
from .nodes.seedream_exhibition_prompt_builder import (
    NODE_CLASS_MAPPINGS as SEEDREAM_EXHIBITION_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEEDREAM_EXHIBITION_DISPLAY_NAME_MAPPINGS,
)
from .nodes.bbox_prompt_reroute import (
    NODE_CLASS_MAPPINGS as BBOX_REROUTE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BBOX_REROUTE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.sam3_complex_collector import (
    NODE_CLASS_MAPPINGS as SAM3_COMPLEX_COLLECTOR_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAM3_COMPLEX_COLLECTOR_DISPLAY_NAME_MAPPINGS,
)
from .nodes.polygon_mask import (
    NODE_CLASS_MAPPINGS as SIMPLE_POLYGON_MASK_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_POLYGON_MASK_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(BOOLEAN_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BOOLEAN_HIERARCHY_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BOOLEAN_GROUP_CONTROLLER_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SEEDREAM_EXHIBITION_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BBOX_REROUTE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SAM3_COMPLEX_COLLECTOR_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SIMPLE_POLYGON_MASK_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_HIERARCHY_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_GROUP_CONTROLLER_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SEEDREAM_EXHIBITION_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BBOX_REROUTE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SAM3_COMPLEX_COLLECTOR_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SIMPLE_POLYGON_MASK_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
