import test from 'node:test';
import assert from 'node:assert/strict';
import {OptimizationRevisions,freezeSnapshot,inspectTarget,matchesSnapshot,restoreSuggestion,applySuggestions,ensureIdentity,forkDocumentIdentity,prepareWorkflowIdentity,NAMESPACE} from '../web/prompt_optimization_model.mjs';
const identity={documentId:'doc',tableId:'table'};
function table(){return {fields:[{id:'scene',name:'画面',type:'text'},{id:'p',name:'图片提示词',type:'json',presentation:'prompt',promptTemplate:{kind:'column-template',version:1,segments:[{type:'column',fieldId:'scene'}]}},{id:'q',name:'视频提示词',type:'json',presentation:'prompt'}],records:[{id:'r',selected:false,values:{scene:'雨后的街道',q:{kind:'column-template',version:1,segments:[{type:'text',text:'女孩合上书，然后起身。'}]}}},{id:'r2',values:{scene:'白猫'}},{id:'empty',values:{}}],meta:{}};}
const target=(r='r',f='p')=>({...identity,recordId:r,fieldId:f});
test('structured dynamic references freeze and round-trip without materializing text',async()=>{
 const t=table(),rev=new OptimizationRevisions(),f=await freezeSnapshot(t,target(),rev,{begin:true,nonce:'test'});
 assert.deepEqual(f.wire.input.protected_tokens,['⟦DAE_REF_test_0001⟧']);assert.equal(f.wire.input.reference_context[0].text,'雨后的街道');
 const result=restoreSuggestion(f,f.wire.input.prompt_text+'。层次清晰。');assert.equal(result.status,'valid');assert.deepEqual(result.document.segments[0],{type:'column',fieldId:'scene'});assert.equal(result.document.segments[1].text,'。层次清晰。');
 assert.equal(t.records[0].values.p,undefined);assert.equal(JSON.parse(f.wire.inputText).optimization_requirements,f.wire.requirements);
});
test('default requirement, input order, digest and nonce are frozen',async()=>{const t=table(),rev=new OptimizationRevisions();const f=await freezeSnapshot(t,target(),rev,{requirements:'  ',nonce:'n'});assert.deepEqual(Object.keys(f.wire.input),['purpose','optimization_requirements','prompt_text','protected_tokens','reference_context']);assert.match(f.wire.snapshotDigest,/^[a-f0-9]{64}$/);assert.equal(f.wire.requirements,'提升清晰度和可执行性，消除重复与含混表达，保持原意，不主动扩写。');});
test('repeated reference occurrences retain independent tokens and anchors',async()=>{const t=table();t.fields[1].promptTemplate.segments.push({type:'text',text:'镜中也出现'},{type:'column',fieldId:'scene'});const f=await freezeSnapshot(t,target(),new OptimizationRevisions());assert.equal(f.wire.input.protected_tokens.length,2);assert.notEqual(...f.wire.input.protected_tokens);assert.throws(()=>restoreSuggestion(f,[...f.wire.input.protected_tokens].reverse().join('')),/保护标记/);assert.throws(()=>restoreSuggestion(f,f.wire.input.protected_tokens[0]),/保护标记/);});
test('empty, truncated, fenced, forged and reserved output cannot apply',async()=>{const f=await freezeSnapshot(table(),target(),new OptimizationRevisions());for(const text of ['', '```text\na\n```',f.wire.input.prompt_text+'⟦DAE_REF_fake_0001⟧',f.wire.input.prompt_text+'DAE_REF_broken',f.wire.input.prompt_text+'@image_1'])assert.throws(()=>restoreSuggestion(f,text));assert.throws(()=>restoreSuggestion(f,f.wire.input.prompt_text,{status:'incomplete'}),/完整/);});
test('unchanged creates neither row override nor history',async()=>{const t=table(),rev=new OptimizationRevisions(),f=await freezeSnapshot(t,target(),rev,{begin:true});let count=0;const result=applySuggestions({table:t,identity,revisions:rev,items:[{requestId:'a',frozen:f,suggestion:restoreSuggestion(f,f.wire.input.prompt_text)}],change:()=>count++});assert.equal(count,0);assert.deepEqual(result.applied,[]);assert.equal(t.records[0].values.p,undefined);});
test('apply one inherited cell and undo preserve template, other rows and media receipts',async()=>{let t=table();t.records[0].meta={generationColumns:{g:{requestId:'media-id',phase:'running'}},generationSettings:{p:{g:{model:'fixed'}}}};const before=structuredClone(t),rev=new OptimizationRevisions(),f=await freezeSnapshot(t,target(),rev,{begin:true});const suggestion=restoreSuggestion(f,f.wire.input.prompt_text+'。层次清晰。');let history=[];const result=applySuggestions({table:t,identity,revisions:rev,items:[{requestId:'a',frozen:f,suggestion}],change:fn=>{history.push(structuredClone(t));fn(t);}});assert.deepEqual(result.applied,['a']);assert.equal(history.length,1);assert.deepEqual(t.fields,before.fields);assert.deepEqual(t.records[1],before.records[1]);assert.deepEqual(t.records[0].meta,before.records[0].meta);rev.observe(t);t=history[0];rev.observe(t);assert.equal(t.records[0].values.p,undefined);assert.equal(matchesSnapshot(t,identity,rev,f),false);});
test('per-field revisions isolate parallel image/video requests and unrelated edits',async()=>{const t=table(),rev=new OptimizationRevisions(),p=await freezeSnapshot(t,target(),rev,{begin:true}),q=await freezeSnapshot(t,target('r','q'),rev,{begin:true});t.records[1].values.scene='其他';rev.observe(t);assert.ok(matchesSnapshot(t,identity,rev,p));assert.ok(matchesSnapshot(t,identity,rev,q));t.records[0].values.scene='变化';rev.observe(t);assert.equal(matchesSnapshot(t,identity,rev,p),false);assert.ok(matchesSnapshot(t,identity,rev,q));t.records[0].values.scene='雨后的街道';rev.observe(t);assert.equal(matchesSnapshot(t,identity,rev,p),false);});
test('batch applies valid entries in one history and skips conflicts',async()=>{const t=table(),rev=new OptimizationRevisions(),a=await freezeSnapshot(t,target(),rev,{begin:true}),b=await freezeSnapshot(t,target('r2'),rev,{begin:true});t.records[1].values.scene='已变';rev.observe(t);let histories=0;const result=applySuggestions({table:t,identity,revisions:rev,items:[a,b].map((f,i)=>({requestId:String(i),frozen:f,suggestion:restoreSuggestion(f,f.wire.input.prompt_text+'。清晰。')})),change:fn=>{histories++;fn(t);}});assert.equal(histories,1);assert.deepEqual(result.applied,['0']);assert.equal(result.conflicts.length,1);});
test('missing row/field and invalid reference fail preparation',async()=>{const t=table(),rev=new OptimizationRevisions();await assert.rejects(freezeSnapshot(t,target('empty'),rev));t.fields=t.fields.filter(f=>f.id!=='scene');await assert.rejects(freezeSnapshot(t,target(),rev));});
test('legacy metadata/inclusion and asset identities survive; media URL never goes in input',async()=>{const t=table();t.fields.push({id:'assets',type:'assets',name:'素材'});t.records[0].values.assets=[{id:'asset',name:'猫',url:'/view?filename=private.png'}];t.records[0].values.p={version:1,compilerVersion:1,segments:[{type:'ref',refId:'ref'},{type:'text',text:'站在门口'}],references:[{refId:'ref',fieldId:'assets',assetId:'asset',included:true,role:'reference'}],sourceState:'keep'};const f=await freezeSnapshot(t,target(),new OptimizationRevisions());assert.doesNotMatch(f.wire.inputText,/private.png|\/view/);const result=restoreSuggestion(f,f.wire.input.prompt_text+'。');assert.deepEqual(result.document.references,t.records[0].values.p.references);assert.equal(result.document.sourceState,'keep');});
test('frame roles and generation configuration are protected, not inferred from media',async()=>{const t=table();t.fields.push({id:'g',presentation:'generation',generation:{promptFieldId:'p',kind:'video',model:'fixed'}});t.fields[1].promptTemplate.segments=[{type:'frame',generationFieldId:'g',role:'first'},{type:'frame',generationFieldId:'g',role:'last'},{type:'text',text:'固定镜头'}];const f=await freezeSnapshot(t,target(),new OptimizationRevisions());assert.equal(f.wire.purpose,'video');assert.deepEqual(f.wire.input.reference_context.map(x=>x.role),['first','last']);assert.deepEqual(restoreSuggestion(f,f.wire.input.prompt_text+'。').document.segments.slice(0,2),t.fields[1].promptTemplate.segments.slice(0,2));});
test('saved revision high water survives history restore, copies get new identities',()=>{const graph={extra:{},_nodes:[]},node={};const first=ensureIdentity(graph,node);assert.deepEqual(ensureIdentity(graph,node),first);assert.notEqual(ensureIdentity(graph,node,{duplicate:true}).tableId,first.tableId);graph._nodes=[node];forkDocumentIdentity(graph);assert.notEqual(graph.extra[NAMESPACE].documentId,first.documentId);const rev=new OptimizationRevisions({'x':{revision:8,requestSeq:4,stamp:'x'}});rev.merge({'x':{revision:1,requestSeq:2}});assert.equal(rev.serialize().x.revision,8);assert.equal(rev.serialize().x.requestSeq,4);});
test('same visible text but changed template/override semantics invalidates snapshot',async()=>{const t=table(),rev=new OptimizationRevisions(),f=await freezeSnapshot(t,target(),rev,{begin:true});t.records[0].values.p=structuredClone(t.fields[1].promptTemplate);rev.observe(t);assert.equal(matchesSnapshot(t,identity,rev,f),false);});
test('plain strings retain representation and do not change external configuration',async()=>{const t=table();t.fields[1]={id:'p',name:'提示词',type:'text'};t.records[0].values.p='白猫，白色的猫。';const f=await freezeSnapshot(t,target(),new OptimizationRevisions());assert.equal(restoreSuggestion(f,'一只白猫。').document,'一只白猫。');});

test('public workflow load hook separates native Save As and Duplicate but preserves raw file copies',()=>{const data={id:'native-old',extra:{[NAMESPACE]:{version:1,documentId:'doc',nativeWorkflowId:'native-old'}},nodes:[{properties:{[NAMESPACE]:{tableId:'table',batches:['original']}}}]};prepareWorkflowIdentity(data);assert.equal(data.extra[NAMESPACE].documentId,'doc');const duplicate=structuredClone(data);duplicate.id='native-new';prepareWorkflowIdentity(duplicate);assert.notEqual(duplicate.extra[NAMESPACE].documentId,'doc');assert.notEqual(duplicate.nodes[0].properties[NAMESPACE].tableId,'table');assert.deepEqual(duplicate.nodes[0].properties[NAMESPACE].batches,[]);assert.equal(data.nodes[0].properties[NAMESPACE].tableId,'table');});
