import test from 'node:test';
import assert from 'node:assert/strict';
import {newStoryboardTable,importRows,writeGenerationResults} from '../web/storyboard_table_adapter.mjs';
import {clone,SnapshotHistory,duplicateSelected} from '../web/data_table_model.mjs';
import {applyPromptResults,PromptRequests,promptField,promptState,promptFingerprint} from '../web/table_prompt_model.mjs';
const document=()=>({version:1,compilerVersion:1,segments:[{type:'text',text:'scene'}],references:[],sourceFingerprint:'backend',editOrigin:'parsed'});
function fixture(){const t=newStoryboardTable();importRows(t,{shots:[{id:'r',image_prompt:'scene'}]},'append');return t;}
test('batch is one reversible transaction including column, binding and mode',()=>{const t=fixture(),history=new SnapshotHistory(),before=JSON.stringify(t);applyPromptResults(t,[{recordId:'r',document:document()}]);history.record(before,JSON.stringify(t));assert.equal(t.fields.at(-1).presentation,'prompt');assert.equal(t.meta.prompt_mode,'reviewed');const undone=history.restore(JSON.stringify(t));assert.deepEqual(undone,JSON.parse(before));const redo=history.restore(JSON.stringify(undone),true);assert.equal(redo.meta.prompt_mode,'reviewed');});
test('empty and failed batches do not create fields or mode',()=>{const t=fixture(),before=clone(t);applyPromptResults(t,[{recordId:'r',error:'missing'}]);assert.deepEqual(t,before);});
test('final-only edits, ABA, reload and request reordering reject old responses',()=>{const t=fixture();applyPromptResults(t,[{recordId:'r',document:document()}]);const q=new PromptRequests(),a=q.begin(t,['r']),field=promptField(t),old=clone(t.records[0].values[field]);t.records[0].values[field].segments[0].text='manual';q.observe(t);t.records[0].values[field]=old;assert.equal(q.matches(t,a,'r'),false);const b=q.begin(t,['r']);q.begin(t,['r']);assert.equal(q.matches(t,b,'r'),false);const c=q.begin(t,['r']);q.invalidate();assert.equal(q.matches(t,c,'r'),false);});
test('unrelated column widths and selection preserve valid request',()=>{const t=fixture(),q=new PromptRequests(),token=q.begin(t,['r']);t.fields[0].width=222;t.records[0].selected=false;assert(q.matches(t,token,'r'));});
test('append import keeps existing reference identities and prompt data',()=>{const t=fixture();t.records[0].values.image_url=[{id:'stable',url:'/view?filename=a.png',name:'a'}];applyPromptResults(t,[{recordId:'r',document:document()}]);const before=clone(t.records[0]);importRows(t,{shots:[{id:'next',image_prompt:'next'}]},'append');assert.deepEqual(t.records[0].values,before.values);});
test('duplicate row has own scope and never inherits a paid task identity',()=>{const t=fixture();applyPromptResults(t,[{recordId:'r',document:document()}]);t.records[0].meta={generation:{request:'paid'}};duplicateSelected(t);assert.notEqual(t.records[0].id,t.records[1].id);assert.equal(t.records[1].meta.generation,undefined);assert.equal(promptState(t,t.records[1]).key,'parsed');});
test('late results retain submitted identity and cannot overwrite a newer task or edited prompt',()=>{const t=fixture();applyPromptResults(t,[{recordId:'r',document:document()}]);const row=t.records[0],f=promptField(t),submitted=promptFingerprint(t,row);row.values[f].segments[0].text='edited while running';writeGenerationResults(t,{batch_id:'old',started_at:1,rows:[{shot_id:'r',request_id:'old',phase:'complete',editorFingerprint:submitted,url:'/view?filename=old.mp4'}]});assert.equal(row.meta.generation.fingerprint,submitted);assert.equal(row.values[f].segments[0].text,'edited while running');assert(!row.values.video_result?.length);writeGenerationResults(t,{batch_id:'new',started_at:2,rows:[{shot_id:'r',request_id:'new',phase:'running',editorFingerprint:promptFingerprint(t,row)}]});writeGenerationResults(t,{batch_id:'old',started_at:1,rows:[{shot_id:'r',request_id:'old',phase:'complete',editorFingerprint:submitted}]});assert.equal(row.meta.generation.request,'new');});
