import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeTable,clone,addRecord,setValue} from '../web/data_table_model.mjs';
import {promptState,promptFingerprint,PromptRequests,applyPromptResults} from '../web/table_prompt_model.mjs';
import {effectivePrompt,resolveColumnPrompt,setColumnTemplate,toColumnPrompt} from '../web/table_prompt_template.mjs';
const doc={kind:'column-template',version:1,segments:[{type:'column',fieldId:'text'},{type:'text',text:' 使用 '},{type:'column',fieldId:'image'},{type:'text',text:' 再次 '},{type:'column',fieldId:'image'}]};
function fixture(){return normalizeTable({fields:[{id:'text',name:'描述',type:'longtext'},{id:'image',name:'参考图',type:'content',video_reference:false},{id:'prompt',name:'提示词',type:'json',presentation:'prompt'}],records:[{id:'one',values:{text:'第一行',image:[{id:'a',url:'/view?filename=a.png'}]}},{id:'two',values:{text:'第二行',image:[{id:'b',url:'/view?filename=b.png'}]}}],meta:{prompt_config:{bindings:{final_prompt:'prompt'}}}});}
test('one shared template resolves same-row text and media, replacement and rename keep relationships',()=>{const t=fixture();setColumnTemplate(t,'prompt',doc);for(const r of t.records){const resolved=resolveColumnPrompt(effectivePrompt(t,r,'prompt'),t,r);assert.equal(resolved.segments[0].text,r.values.text);assert.equal(resolved.references.length,1);assert.equal(resolved.references[0].assetId,r.values.image[0].id);assert.equal(promptState(t,r).error,'');}const original=clone(t.fields[2].promptTemplate);t.fields.reverse();t.fields.find(f=>f.id==='image').name='新名称';t.records[0].values.image=[{id:'new',url:'/view?filename=new.png'}];assert.equal(resolveColumnPrompt(doc,t,t.records[0]).references[0].assetId,'new');assert.deepEqual(t.fields.find(f=>f.id==='prompt').promptTemplate,original);});
test('column updates preserve legacy and explicit row overrides, reset/new row inherit and reload retains bindings',()=>{const t=fixture(),legacy={version:1,compilerVersion:1,segments:[{type:'text',text:'旧正文'}],references:[]};t.records[0].values.prompt=legacy;setColumnTemplate(t,'prompt',doc);assert.deepEqual(effectivePrompt(t,t.records[0],'prompt'),legacy);setValue(t,'two','prompt',{...doc,segments:[{type:'text',text:'仅此行'}]});setColumnTemplate(t,'prompt',{...doc,segments:[{type:'text',text:'新模板'}]});assert.equal(effectivePrompt(t,t.records[1],'prompt').segments[0].text,'仅此行');t.records[1].values.prompt='';addRecord(t);const reload=normalizeTable(JSON.stringify(t));assert.equal(effectivePrompt(reload,reload.records[1],'prompt').segments[0].text,'新模板');assert.equal(effectivePrompt(reload,reload.records.at(-1),'prompt').segments[0].text,'新模板');setColumnTemplate(t,'prompt',doc,{replaceRows:true});assert.ok(t.records.every(r=>!r.values.prompt));});
test('missing column, empty media and invalid multi-media are distinct; no cross-row fallback',()=>{const t=fixture();setColumnTemplate(t,'prompt',doc);t.records[0].values.image=[];assert.match(promptState(t,t.records[0]).error,/本行缺少参考素材/);assert.equal(promptState(t,t.records[1]).error,'');t.records[0].values.image=[...t.records[1].values.image,...t.records[1].values.image];assert.match(promptState(t,t.records[0]).error,/只能有一个/);t.fields=t.fields.filter(f=>f.id!=='image');assert.match(promptState(t,t.records[1]).error,/引用列已删除/);});
test('in-flight changes and fingerprints follow template/value edits; parsing cannot freeze dynamic template',()=>{const t=fixture();setColumnTemplate(t,'prompt',doc);const requests=new PromptRequests(),token=requests.begin(t,['one']),before=promptFingerprint(t,t.records[0]);t.records[0].values.text='更新';assert.notEqual(promptFingerprint(t,t.records[0]),before);assert.equal(requests.matches(t,token,'one'),false);const next=requests.begin(t,['two']);setColumnTemplate(t,'prompt',{...doc,segments:[{type:'text',text:'更新模板'}]});assert.equal(requests.matches(t,next,'two'),false);applyPromptResults(t,[{recordId:'one',document:{version:1,compilerVersion:1,segments:[],references:[]}}]);assert.equal(t.records[0].values.prompt,undefined);});
test('legacy conversion binds field identity, never image name or index',()=>{assert.deepEqual(toColumnPrompt({segments:[{type:'ref',refId:'x'}],references:[{refId:'x',fieldId:'image',assetId:'old'}]}).segments,[{type:'column',fieldId:'image'}]);});
