from .node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

from .target_only import NODE_CLASS_MAPPINGS as TARGET_NODES, NODE_DISPLAY_NAME_MAPPINGS as TARGET_NAMES
NODE_CLASS_MAPPINGS.update(TARGET_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(TARGET_NAMES)
