"""Compile the single UI copy source. --check is read-only; never edits saved user state."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / 'content/badge87'


def build(check=False):
    data = json.loads((CONTENT / 'ui.zh-CN.json').read_text(encoding='utf-8'))
    messages = data['messages']
    if not all(isinstance(v, str) for v in messages.values()):
        raise ValueError('UI messages must be strings.')
    text = '// Generated by tools/build_badge87_content.py; edit content/badge87/ui.zh-CN.json.\n'
    text += 'export const messages = Object.freeze(' + json.dumps(messages, ensure_ascii=False, indent=2) + ');\n'
    output = ROOT / 'web/badge_ui_catalog.mjs'
    if check:
        if not output.exists() or output.read_text(encoding='utf-8') != text:
            raise ValueError('Generated UI catalog is stale. Run tools/build_badge87_content.py.')
    else:
        output.write_text(text, encoding='utf-8')
    binding = json.loads((CONTENT / 'ui.workflow-bindings.json').read_text(encoding='utf-8'))
    path = ROOT / binding['file']
    workflow = json.loads(path.read_text(encoding='utf-8'))
    changed = False
    for entry in binding['bindings']:
        target = workflow
        for part in entry['path'][:-1]:
            target = target[part]
        key = entry['path'][-1]
        value = messages[entry['key']]
        if target[key] != value:
            if check:
                raise ValueError(f'Workflow default is stale: {entry["key"]}')
            target[key] = value
            changed = True
    if changed:
        path.write_text(json.dumps(workflow, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'Badge UI content {"verified" if check else "built"}: {len(messages)} messages.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    build(parser.parse_args().check)
