import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const evidenceDir=process.env.CREATIVE_EVIDENCE?pathToFileURL(resolve(process.env.CREATIVE_EVIDENCE)+'/'):new URL('../docs/architecture/native-gallery/',import.meta.url);
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../frontend/package.json',import.meta.url));
const {chromium}=require('playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1920,height:1200}});
const errors=[],prompts=[];let buttonURL;
page.on('request',r=>{if(r.url().includes('/creative_button.mjs'))buttonURL=r.url();});
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/prompt',r=>{if(r.request().method()==='POST'){prompts.push(r.request().url());return r.abort();}return r.continue();});
await page.route('**/comfytv/assets?*',r=>r.fulfill({json:{assets:[],total:0}}));
const fixture=JSON.parse(await readFile(new URL('../examples/creative_canvas/Creative Canvas Controls.json',import.meta.url),'utf8'));
try {
 await page.goto(process.env.COMFY_URL||'http://127.0.0.1:8000/');
 await page.waitForFunction(()=>window.app?.daelabCreativeCanvas);
 await page.evaluate(async data=>{await app.loadGraphData(data);app.daelabCreativeCanvas.show();},fixture);
 await page.waitForFunction(()=>document.querySelectorAll('.dae-libtv [data-creative-button]').length>=5);
 const result=await page.evaluate(async buttonURL=>{
  const checks=[];const ok=(condition,name)=>{if(!condition)throw Error(name);checks.push(name);};
  const nodes=app.graph._nodes.filter(n=>n.type==='DAELAB.LibTV.VideoGenerate');
  const [a,b]=nodes;const get=n=>n.widgets.find(w=>w.name==='request_id').value;
  const [fresh,restore]=a.__libtvPanel.creativeButtons;
  const beforeB=get(b),beforeA=get(a);fresh.click();
  ok(get(a)!==beforeA&&get(b)===beforeB,'request IDs remain independent');
  const heading=document.querySelector(`article[data-node-id="${a.id}"] header button`);
  const expanded=heading.getAttribute('aria-expanded');heading.click();ok(heading.getAttribute('aria-expanded')!==expanded,'card shared action works');heading.click();
  const nativeFetch=window.fetch;let calls=0,resolve;
  window.fetch=(...args)=>String(args[0]).startsWith('/history?')?(calls++,new Promise(r=>resolve=r)):nativeFetch(...args);
  const task=restore.onclick(new Event('click'));restore.click();
  ok(calls===1&&restore.disabled&&restore.getAttribute('aria-busy')==='true','async action blocks repeated clicks');
  resolve({ok:true,json:async()=>({})});await task;window.fetch=nativeFetch;
  ok(!restore.disabled&&!restore.hasAttribute('aria-busy'),'async completion restores button');
  app.daelabCreativeCanvas.hide();
  const original=fresh.onclick;
  ok(!fresh.hasAttribute('data-creative-button'),'exit removes creative binding');
  const graphStyle=getComputedStyle(fresh).backgroundColor;
  for(let i=0;i<3;i++){app.daelabCreativeCanvas.show();app.daelabCreativeCanvas.hide();ok(fresh.onclick===original,'mode roundtrip restores exact original handler '+i);}
  ok(getComputedStyle(fresh).backgroundColor===graphStyle,'graph mode styles remain unchanged');
  app.daelabCreativeCanvas.show();
  const url=buttonURL;
  const {bindCreativeButton}=await import(url);
  const test=document.createElement('button');document.body.append(test);
  let finish;const action=()=>new Promise(r=>finish=r);test.onclick=action;
  const release=bindCreativeButton(test);ok(bindCreativeButton(test)===release,'binding is idempotent');
  const pending=test.onclick(new Event('click'));release();ok(test.onclick===action&&!test.disabled,'release during async restores original state');
  const again=bindCreativeButton(test);test.setAttribute('aria-busy','new-owner');finish();await pending;
  ok(test.getAttribute('aria-busy')==='new-owner','stale completion cannot modify new binding');again();test.remove();
  const rejected=document.createElement('button');rejected.onclick=async()=>{throw Error('expected');};const undo=bindCreativeButton(rejected);await rejected.onclick(new Event('click')).catch(()=>{});ok(!rejected.disabled&&!rejected.hasAttribute('aria-busy'),'rejection clears busy state');undo();
  return {checks,sharedButtons:document.querySelectorAll('[data-creative-button]').length};
 },buttonURL);
 const toggle=page.locator('article[data-node-id="2"] header button').first();
 const expanded=await toggle.getAttribute('aria-expanded');await toggle.focus();
 await page.keyboard.press('Enter');assert.notEqual(await toggle.getAttribute('aria-expanded'),expanded);await page.keyboard.press('Enter');assert.equal(await toggle.getAttribute('aria-expanded'),expanded);
 result.checks.push('native keyboard activation');
 const saved=await page.evaluate(()=>app.graph.serialize());
 await page.reload();await page.waitForFunction(()=>window.app?.daelabCreativeCanvas);
 await page.evaluate(async data=>{await app.loadGraphData(data);app.daelabCreativeCanvas.show();},saved);
 await page.waitForFunction(()=>document.querySelectorAll('.dae-libtv [data-creative-button]').length>=5);
 result.checks.push('serialized workflow reload restores shared buttons');
 assert.deepEqual(errors,[]);assert.deepEqual(prompts,[]);
 const dir=evidenceDir;
 await mkdir(dir,{recursive:true});
 await page.screenshot({path:new URL('button-pilot.png',dir).pathname.replace(/^\/(\w:)/,'$1')});
 await writeFile(new URL('button-pilot-verification.json',dir),JSON.stringify({...result,errors,prompts},null,2));
 console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
