const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{
 const out=process.argv[2];fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'});const context=await browser.newContext({viewport:{width:1600,height:1000},permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();page.setDefaultTimeout(15000);const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const pass=s=>{checks.push(s);console.log('PASS',s);};
 try{
 await page.goto('http://127.0.0.1:8199');await page.waitForFunction(()=>window.app?.daelabCreativeCanvas);await page.waitForTimeout(1000);await page.keyboard.press('Escape');
 const demo=JSON.parse(fs.readFileSync(path.join(out,'../upload/Upload Demo.json'),'utf8'));await page.evaluate(async s=>app.loadGraphData(s),demo);await page.waitForFunction(()=>document.querySelector('.dae-creative .dae-upload img')?.naturalWidth>0);
 const view=()=>page.evaluate(()=>({...app.graph.extra.daelabCreativeCanvasV1.viewport}));
 await page.mouse.move(1400,850);let before=await view();await page.mouse.wheel(0,120);await page.waitForTimeout(200);let after=await view();assert.equal(after.zoom,before.zoom);assert.equal(after.y,before.y-120);pass('Wheel vertically pans');
 before=await view();await page.keyboard.down('Shift');await page.mouse.wheel(0,120);await page.keyboard.up('Shift');await page.waitForTimeout(200);after=await view();assert.equal(after.y,before.y);assert.equal(after.x,before.x-120);pass('Shift wheel horizontally pans');
 before=await view();await page.keyboard.down('Control');await page.mouse.wheel(0,-120);await page.keyboard.up('Control');await page.waitForTimeout(200);after=await view();assert.ok(after.zoom>before.zoom);pass('Ctrl wheel zooms');
 await page.evaluate(()=>app.daelabCreativeCanvas.fit());
 const image=page.locator('.dae-creative-card[data-node-id="1"]');await image.locator('img').click();await page.keyboard.press('Control+c');await page.mouse.move(600,400);await page.keyboard.press('Control+v');await page.waitForFunction(()=>app.graph._nodes.length===3);await page.keyboard.press('Control+v');await page.waitForFunction(()=>app.graph._nodes.length===4);
 const copied=await page.evaluate(()=>app.graph._nodes.map(n=>({id:n.id,value:n.widgets.find(w=>w.name==='asset_data').value,outputs:n.outputs.map(o=>o.links)})));const original=copied.find(n=>String(n.id)==='1');for(const copy of copied.filter(n=>!['1','2'].includes(String(n.id))))assert.equal(copy.value,original.value);assert.equal(new Set(copied.map(n=>n.id)).size,4);assert.ok(copied[2].outputs.every(l=>!l?.length));pass('Real Ctrl+C/V creates independent selected-node copies');
 await page.evaluate(()=>app.daelabCreativeCanvas.fit());const video=page.locator('.dae-creative-card[data-node-id="2"]');await video.locator('.dae-creative-heading strong').click();await page.keyboard.press('Control+c');await page.keyboard.press('Control+v');await page.waitForFunction(()=>app.graph._nodes.length===5);await page.evaluate(()=>app.daelabCreativeCanvas.fit());pass('Video node also copies');
 const last=page.locator('.dae-creative-card').last();await last.locator('strong').dblclick();const input=last.locator('.dae-creative-heading input');await input.fill('文字复制测试');await input.selectText();await page.keyboard.press('Control+c');await page.keyboard.press('End');await page.keyboard.press('Control+v');assert.equal(await input.inputValue(),'文字复制测试文字复制测试');assert.equal(await page.evaluate(()=>app.graph._nodes.length),5);await input.press('Enter');pass('Editable text retains native clipboard behavior');
 const libId=await page.evaluate(()=>{const n=app.daelabCreativeCanvas.add('DAELAB.LibTV.VideoGenerate');n.widgets.find(w=>w.name==='prompt').value='复制参数验证';n.widgets.find(w=>w.name==='request_id').value='original-request';app.graph.extra.daelabCreativeCanvasV1.cards[n.id].expanded=false;app.daelabCreativeCanvas.sync();app.daelabCreativeCanvas.fit();return n.id;});await page.locator(`.dae-creative-card[data-node-id="${libId}"] .dae-creative-heading strong`).click();await page.keyboard.press('Control+c');await page.keyboard.press('Control+v');await page.waitForFunction(()=>app.graph._nodes.length===7);const configs=await page.evaluate(()=>app.graph._nodes.filter(n=>n.type==='DAELAB.LibTV.VideoGenerate').map(n=>({prompt:n.widgets.find(w=>w.name==='prompt').value,request:n.widgets.find(w=>w.name==='request_id').value})));assert.ok(configs.every(n=>n.prompt==='复制参数验证'));assert.equal(new Set(configs.map(n=>n.request)).size,2);pass('Functional node parameters copy with a fresh request identity');
await page.evaluate(()=>{const s=app.graph.extra.daelabCreativeCanvasV1;app.graph._nodes.forEach((n,i)=>Object.assign(s.cards[n.id],{x:i%3*720,y:Math.floor(i/3)*570}));app.daelabCreativeCanvas.sync();app.daelabCreativeCanvas.fit();});await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'copies.png')});
 const saved=await page.evaluate(()=>app.graph.serialize());await page.reload();await page.waitForFunction(()=>window.app?.daelabCreativeCanvas);await page.waitForTimeout(1200);await page.evaluate(async s=>app.loadGraphData(s),saved);await page.waitForFunction(()=>document.querySelectorAll('.dae-creative .dae-upload img').length===3&&document.querySelectorAll('.dae-creative .dae-upload video').length===2);pass('Copies persist after save/reload');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({checks,errors},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
