const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{
 const out=process.argv[2];fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true,channel:'chrome'});const context=await b.newContext({viewport:{width:1600,height:1000},permissions:['clipboard-read','clipboard-write']});const p=await context.newPage();p.setDefaultTimeout(15000);const errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));const pass=s=>{checks.push(s);console.log('PASS',s);};
 try{
 await p.goto('http://127.0.0.1:8199');await p.waitForFunction(()=>window.app?.daelabCreativeCanvas);await p.waitForTimeout(1000);await p.keyboard.press('Escape');await p.evaluate(async s=>app.loadGraphData(s),JSON.parse(fs.readFileSync(path.join(out,'../upload/Upload Demo.json'),'utf8')));await p.waitForFunction(()=>document.querySelector('.dae-creative .dae-upload img')?.naturalWidth>0);
 await p.evaluate(()=>{const s=app.graph.extra.daelabCreativeCanvasV1;Object.assign(s.viewport,{x:0,y:0,zoom:1});app.daelabCreativeCanvas.hide();app.daelabCreativeCanvas.show();app.graph._nodes.forEach((n,i)=>Object.assign(s.cards[n.id],{x:100+i*430,y:100,width:350}));app.daelabCreativeCanvas.sync();});await p.waitForTimeout(300);
 const root=await p.locator('.dae-creative').boundingBox();const view=()=>p.evaluate(()=>({...app.graph.extra.daelabCreativeCanvasV1.viewport}));const before=await view();
 await p.mouse.move(root.x+50,root.y+50);await p.mouse.down();await p.mouse.move(root.x+940,root.y+500,{steps:12});await p.screenshot({path:path.join(out,'marquee.png')});await p.mouse.up();assert.deepEqual(await view(),before);assert.equal(await p.locator('.dae-creative-card[data-selected=true]').count(),2);pass('Left drag box-selects both nodes without panning');
 await p.mouse.move(root.x+250,root.y+270);await p.mouse.down({button:'middle'});await p.mouse.move(root.x+310,root.y+300,{steps:8});await p.mouse.up({button:'middle'});const moved=await view();assert.equal(moved.x,before.x+60);assert.equal(moved.y,before.y+30);assert.equal(await p.locator('.dae-creative-card[data-selected=true]').count(),2);pass('Middle drag pans even over media and preserves selection');
 const positions=()=>p.evaluate(()=>app.graph._nodes.map(n=>({id:n.id,...app.graph.extra.daelabCreativeCanvasV1.cards[n.id]})));const old=await positions();const heading=await p.locator('.dae-creative-card .dae-creative-heading strong').first().boundingBox();await p.mouse.move(heading.x+20,heading.y+10);await p.mouse.down();await p.mouse.move(heading.x+70,heading.y+50,{steps:8});await p.mouse.up();const now=await positions();for(const row of now){const prev=old.find(n=>n.id===row.id);assert.equal(row.x,prev.x+50);assert.equal(row.y,prev.y+40);}pass('Dragging a selected node moves the whole selection');
 await p.keyboard.press('Control+c');await p.mouse.move(root.x+300,root.y+550);await p.keyboard.press('Control+v');await p.waitForFunction(()=>app.graph._nodes.length===4);assert.equal(await p.locator('.dae-creative-card[data-selected=true]').count(),2);const copies=await p.locator('.dae-creative-card[data-selected=true]').evaluateAll(es=>es.map(e=>({x:parseFloat(e.style.left),y:parseFloat(e.style.top)})));assert.equal(Math.abs(copies[1].x-copies[0].x),430);pass('Multi-node clipboard preserves relative positions');
 await p.keyboard.press('Delete');await p.waitForFunction(()=>app.graph._nodes.length===2);pass('Delete removes only the selected copies');
 await p.mouse.move(root.x+20,root.y+20);await p.mouse.down();await p.mouse.move(root.x+150,root.y+90);await p.keyboard.press('Escape');await p.mouse.up();assert.equal(await p.locator('.dae-creative-marquee').isVisible(),false);pass('Escape cancels marquee');
 await p.evaluate(()=>app.daelabCreativeCanvas.fit());await p.screenshot({path:path.join(out,'result.png')});await p.evaluate(async s=>app.loadGraphData(s),JSON.parse(fs.readFileSync(path.join(out,'../connections/Single Material Outlet.json'),'utf8')));await p.waitForFunction(()=>document.querySelector('.dae-creative .dae-upload img')?.naturalWidth>0);await p.evaluate(()=>app.daelabCreativeCanvas.fit());await p.waitForTimeout(400);const canvas=await p.locator('.dae-creative').boundingBox();await p.mouse.move(canvas.x+10,canvas.y+10);await p.mouse.down();await p.mouse.move(canvas.x+canvas.width-15,canvas.y+canvas.height-50,{steps:10});await p.mouse.up();assert.equal(await p.locator('.dae-creative-card[data-selected=true]').count(),4);await p.keyboard.press('Control+c');await p.keyboard.press('Control+v');await p.waitForFunction(()=>app.graph._nodes.length===8);assert.equal(await p.evaluate(()=>Object.values(app.graph.links).length),8);pass('Copied selection restores internal links between new nodes');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({checks,errors},null,2));
 }finally{await b.close();}
})().catch(e=>{console.error(e);process.exit(1);});
