const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{
 const out=process.argv[2];fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1700,height:1100}});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const checks=[];const pass=s=>{checks.push(s);console.log('PASS',s);};
 try{
 await page.goto('http://127.0.0.1:8199');await page.waitForFunction(()=>window.app?.daelabCreativeCanvas);await page.waitForTimeout(700);await page.keyboard.press('Escape');
 const saved=JSON.parse(fs.readFileSync(path.join(out,'../upload/Upload Demo.json'),'utf8'));await page.evaluate(async s=>app.loadGraphData(s),saved);
 const ids=await page.evaluate(()=>{const [image,video]=app.graph._nodes;const target=app.daelabCreativeCanvas.add('DAELAB.LibTV.VideoGenerate');const clip=app.daelabCreativeCanvas.add('ComfyTV.VideoClipStage');const layout=app.graph.extra.daelabCreativeCanvasV1.cards;[image,video,target,clip].forEach((n,i)=>Object.assign(layout[n.id],{x:Math.floor(i/2)*780,y:i%2*560,width:600,expanded:false}));app.daelabCreativeCanvas.sync();app.daelabCreativeCanvas.fit();return {image:image.id,video:video.id,target:target.id,clip:clip.id};});
 const card=id=>page.locator(`.dae-creative-card[data-node-id="${id}"]`);const outlet=id=>card(id).locator('button[data-side=output][data-slot="-1"]');
 assert.equal(await card(ids.image).locator('button[data-side=output]').count(),1);assert.equal(await card(ids.video).locator('button[data-side=output]').count(),1);assert.equal(await card(ids.target).locator('button[data-side=input]').count(),1);assert.equal(await card(ids.target).locator('button[data-side=output]').count(),1);await page.mouse.move(1600,950);await page.waitForTimeout(250);assert.equal(await outlet(ids.image).evaluate(e=>getComputedStyle(e).opacity),'0');await card(ids.image).locator('.dae-creative-heading').hover();await page.waitForTimeout(250);assert.equal(await outlet(ids.image).evaluate(e=>getComputedStyle(e).opacity),'1');const bounds=await card(ids.image).boundingBox(),portBounds=await outlet(ids.image).boundingBox();assert.ok(portBounds.x>bounds.x+bounds.width);await page.screenshot({path:path.join(out,'hover.png')});pass('DAELab nodes have single floating ports, hidden until hover');
 const drag=async (from,to)=>{await from.locator('xpath=ancestor::article').locator('.dae-creative-heading').hover();const a=await from.boundingBox(),b=await to.boundingBox();const fuzzyFrom=await from.getAttribute('data-slot')==='-1',fuzzyTo=await to.getAttribute('data-slot')==='-1';await page.mouse.move(a.x+a.width/2+(fuzzyFrom?28:0),a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2-(fuzzyTo?28:0),b.y+b.height/2,{steps:12});if(fuzzyTo){assert.equal(await to.getAttribute('data-magnetic'),'true');await page.screenshot({path:path.join(out,'magnetic.png')});}await page.mouse.up();await page.waitForTimeout(300);};
 await drag(outlet(ids.image),card(ids.target).locator('.dae-creative-heading strong'));
 const picker=page.getByRole('region',{name:'选择素材用途'});const choices=page.locator('.dae-creative-picker[aria-label="选择素材用途"]');await choices.waitFor();await choices.getByRole('button',{name:'首帧',exact:true}).click();
 let links=await page.evaluate(()=>Object.values(app.graph.links).map(l=>({origin_slot:l.origin_slot,target_slot:l.target_slot})));assert.ok(links.some(l=>l.origin_slot===3&&l.target_slot===0));pass('Drop on card asks for first/last/reference role and resolves native IMAGE');
 await drag(outlet(ids.image),card(ids.target).locator('[data-side=input][data-slot="-1"]'));await choices.getByRole('button',{name:'尾帧',exact:true}).click();pass('Unified input assigns second image connection to last frame');
 await drag(outlet(ids.video),card(ids.clip).locator('.dae-creative-heading strong'));await page.waitForFunction(()=>Object.values(app.graph.links).length===3);pass('Drop video on single-input card connects COMFYTV_VIDEO automatically');
 await drag(card(ids.target).locator('[data-side=input][data-slot="-1"]'),outlet(ids.video));await page.waitForFunction(()=>Object.values(app.graph.links).length===4);pass('Reverse dragging also resolves material output');
 await drag(outlet(ids.image),card(ids.clip).locator('[data-side=input][data-slot="0"]'));assert.equal(await page.evaluate(()=>Object.values(app.graph.links).length),4);pass('Incompatible drop preserves existing connection');
 await drag(outlet(ids.image),card(ids.target).locator('.dae-creative-heading strong'));await choices.waitFor();await page.keyboard.press('Escape');assert.equal(await choices.count(),0);pass('Ambiguous connection cancels without mutation');
 assert.equal(await page.locator('.dae-creative-wires path').count(),4);
 await page.mouse.move(1600,950);await page.waitForTimeout(250);await page.screenshot({path:path.join(out,'connected.png')});
 const workflow=await page.evaluate(()=>app.graph.serialize());fs.writeFileSync(path.join(out,'Single Material Outlet.json'),JSON.stringify(workflow,null,2));
 await page.evaluate(()=>app.daelabCreativeCanvas.hide());await page.evaluate(()=>app.daelabCreativeCanvas.show());assert.equal(await page.locator('.dae-creative-wires path').count(),4);
 await page.reload();await page.waitForFunction(()=>window.app?.daelabCreativeCanvas);await page.waitForTimeout(1200);await page.evaluate(async s=>app.loadGraphData(s),workflow);await page.waitForFunction(()=>document.querySelectorAll('.dae-creative-wires path').length===4);assert.equal(await card(ids.image).locator('button[data-side=output]').count(),1);pass('Mode switch, reload and reopen preserve typed edges and unified anchors');
 await page.waitForFunction(()=>document.querySelector('.dae-creative .dae-upload img')?.naturalWidth>0&&document.querySelector('.dae-creative .dae-upload video')?.readyState>=2);await page.waitForTimeout(350);await page.evaluate(()=>app.daelabCreativeCanvas.fit());await page.screenshot({path:path.join(out,'restored.png')});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({checks,errors},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
