export function studioTheme() {
    if (document.getElementById('dae-studio-theme')) return;
    const style = document.createElement('style'); style.id = 'dae-studio-theme';
    style.textContent = `
.dae-studio{--studio-bg:#17191c;--studio-line:#30343a;--studio-accent:#b6ecd8;background:var(--studio-bg)!important;color:#e5e8eb!important;border:1px solid var(--studio-line)!important;border-radius:12px!important;padding:14px!important;gap:12px!important;font:12px/1.5 'Alibaba PuHuiTi 3',sans-serif!important}
.dae-studio *{box-sizing:border-box;font-family:'Alibaba PuHuiTi 3',sans-serif!important}.dae-studio [hidden]{display:none!important}.dae-studio .studio-footer{flex-shrink:0;max-height:none!important}.dae-studio .studio-tabs{flex-shrink:0}.dae-studio .studio-tabs button{white-space:nowrap}.dae-studio [data-storyboard-scroll]{background:#17191c!important}
.dae-studio :is(input,textarea,select){background:#1d2024!important;border:1px solid #34383f!important;color:#e8eaed!important;border-radius:6px!important;outline:none;font-size:12px!important;padding:6px 8px;min-width:0}
.dae-studio :is(input,textarea,select):focus{border-color:#8acdb5!important;box-shadow:0 0 0 2px #8acdb516}.dae-studio input[type=checkbox]{accent-color:#a0dcc5;width:15px!important;height:15px!important}
.dae-studio button{background:#24282e!important;border:1px solid #383e45!important;color:#cdd2d8!important;border-radius:6px!important;font-size:12px!important;cursor:pointer}.dae-studio button:hover{background:#333940!important;color:#fff!important}.dae-studio button[data-primary]{background:#b6ecd8!important;border-color:#b6ecd8!important;color:#163428!important;font-weight:600}.dae-studio button:disabled{opacity:.4;cursor:default}
.dae-studio table{background:#17191c!important}.dae-studio th{background:#22262b!important;color:#9ea7b2!important;font-size:11px!important;letter-spacing:.2px}.dae-studio td,.dae-studio th,.dae-studio tr{border-color:#2c3036!important}.dae-studio tbody tr:hover{background:#1e2227}.dae-studio td textarea{border-color:transparent!important;background:transparent!important}.dae-studio td textarea:focus{background:#24282e!important;border-color:#8acdb5!important}
.dae-studio [data-drag-kind]{opacity:.38}.dae-studio tr:hover [data-drag-kind],.dae-studio th:hover [data-drag-kind]{opacity:1}
.dae-studio .studio-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;flex:none}.dae-studio .studio-heading strong{font-size:17px;letter-spacing:.4px}.dae-studio .studio-eyebrow{font-size:10px;color:#82bda7;letter-spacing:1.6px}.dae-studio .studio-tabs{display:flex;gap:5px}.dae-studio .studio-tabs button{padding:6px 12px;border-color:transparent!important;background:transparent!important}.dae-studio .studio-tabs button[aria-selected=true]{background:#2c3338!important;color:#c9f4e3!important}
.dae-studio .studio-groups{flex:1;min-height:0;overflow:auto;display:flex;flex-direction:column;gap:10px}.dae-studio .studio-hint{color:#8d98a5;font-size:11px;white-space:pre-wrap}.dae-studio .studio-group{padding:12px;border:1px solid #34383f;border-radius:9px;background:#202429}.dae-studio .studio-group-head{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.dae-studio .studio-group-head input{flex:1;width:100px}.dae-studio .studio-assets{display:flex;gap:8px;overflow:auto;padding-top:10px}.dae-studio .studio-asset{flex:0 0 102px;position:relative}.dae-studio .studio-asset img{width:102px;height:65px;object-fit:cover;border-radius:6px;background:#111}.dae-studio .studio-asset small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#aaa}.dae-studio .studio-asset nav{display:flex;gap:3px}.dae-studio .studio-ref{display:inline-block;margin:2px;position:relative}.dae-studio .studio-ref img{width:54px;height:42px;object-fit:cover;border-radius:5px}.dae-studio .studio-ref small{display:block;font-size:9px;color:#8d98a5}
.dae-studio .studio-results{display:flex;flex-direction:column;gap:8px}.dae-studio .studio-result{border:1px solid #34383f;padding:10px;border-radius:8px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}.dae-studio .studio-result video{width:160px;max-height:100px;border-radius:6px}.dae-studio .studio-result a{color:#b6ecd8}.dae-studio .studio-result span{flex:1;min-width:100px;overflow-wrap:anywhere}
`;
    document.head.append(style);
}
