export function workbenchTheme(){
 if(document.getElementById('dae-workbench-theme'))return;
 const style=document.createElement('style');style.id='dae-workbench-theme';style.textContent=`
.dae-workbench{width:96vw!important;max-width:1800px!important;height:94vh!important;max-height:94vh!important;padding:0!important;overflow:hidden!important;border-radius:16px!important}
.dae-workbench>.daelab-storyboard-panel{height:100%!important;min-height:0!important;max-height:none!important;border:0!important;border-radius:0!important;padding:22px!important}
.dae-workbench .daelab-storyboard-panel button{margin:0}.dae-workbench .dae-table-toolbar>select{flex:none;width:140px}.table-settings{position:relative}.table-settings>summary{cursor:pointer;padding:6px 10px}.table-settings[open]{padding:5px;background:#24282e;border-radius:6px}
.dae-workbench-placeholder{display:flex;gap:16px;align-items:center;justify-content:center;height:100%;color:#a0aab5;background:#191c20;font:14px 'Alibaba PuHuiTi 3',sans-serif}.dae-workbench-placeholder[hidden]{display:none}
.daelab-storyboard-panel .studio-group-head{flex:none;gap:8px}.daelab-storyboard-panel button{min-height:30px;padding:5px 10px}.daelab-storyboard-panel .workbench-expand{white-space:nowrap}.daelab-storyboard-panel .studio-tabs{flex-wrap:wrap;justify-content:flex-end}.daelab-storyboard-panel .studio-heading{align-items:flex-start}
.daelab-storyboard-panel .dae-table td,.daelab-storyboard-panel .dae-table td :is(input,textarea,select){font-size:14px!important}.daelab-storyboard-panel .dae-table th{font-size:12px!important;height:40px!important}.daelab-storyboard-panel .dae-table .table-asset{max-width:96px}.daelab-storyboard-panel .dae-table .table-asset img,.daelab-storyboard-panel .dae-table .table-asset video{width:96px;height:54px;object-fit:cover;cursor:zoom-in}.daelab-storyboard-panel .dae-table .table-asset small{max-width:96px;font-size:11px}
.dae-table[data-density=comfortable]{--dae-prompt-height:140px;--dae-text-card-height:116px}.dae-table[data-density=comfortable] td{height:96px}.dae-table[data-density=compact]{--dae-prompt-height:112px;--dae-text-card-height:88px}.dae-table[data-density=compact] td{height:64px}.dae-table[data-density=compact] .table-asset img,.dae-table[data-density=compact] .table-asset video{width:72px;height:40px}
.dae-table .table-selection-actions{display:flex;gap:6px}.dae-table .table-selection-actions[hidden]{display:none}.dae-table .task-badge{display:inline-block;margin:6px 0;padding:3px 8px;border-radius:5px;font-size:12px;white-space:nowrap;color:#a4ddcb;background:#214136}.dae-table .task-badge[data-state=invalid],.dae-table .task-badge[data-state=changed],.dae-table .task-badge[data-state=recovery]{color:#f2ca84;background:#463722}.dae-table .task-badge[data-state=running],.dae-table .task-badge[data-state=queued]{color:#b1cbfa;background:#263b59}.dae-table td[data-invalid=true]{box-shadow:inset 0 -2px #b78b49}.dae-table input::placeholder,.dae-table textarea::placeholder{color:#6e7885;opacity:1}
.table-task-summary{font-size:12px;color:#a4b6c2;line-height:1.6;flex:none}.table-task-summary[data-invalid=true]{color:#e9c285}.table-task-summary button{margin-left:8px}.dae-media-dialog{width:min(1000px,92vw)!important}.dae-media-dialog :is(img,video){width:100%;height:min(65vh,650px);object-fit:contain;background:#111;border-radius:8px}
.dae-generation-dialog{width:min(760px,94vw)!important}.dae-generation-dialog>.dae-libtv{width:100%!important;height:auto!important;min-height:0!important;max-height:none!important;overflow:visible!important}.dae-generation-dialog>button{float:right}
.dae-workbench [data-expanded=true] .studio-hint{font-size:12px}.dae-workbench .dae-table-scroll{border-radius:9px}.dae-workbench .studio-heading strong{font-size:20px}.dae-workbench .studio-eyebrow{margin-bottom:4px}
@media(max-width:700px){.dae-workbench{width:98vw!important;height:96vh!important;max-height:96vh!important}.dae-workbench>.daelab-storyboard-panel{padding:12px!important}.dae-workbench .studio-heading{flex-wrap:wrap}}
`;document.head.append(style);
}
